In [1]:

from google.colab import auth
from google.cloud import bigquery
import pandas as pd

# Authenticate your Google account
auth.authenticate_user()

# Connect to your cloud project
project_id = "emea-strategic-analytics"
client = bigquery.Client(project=project_id)

print("Connected to BigQuery!")
print("Project:", client.project)

Connected to BigQuery!
Project: emea-strategic-analytics

In [2]:

query = """
SELECT *
FROM `emea-strategic-analytics.emea_analytics.raw_erp_billing`
"""

df_raw = client.query(query).to_dataframe()

print("Rows:", len(df_raw))
print("Columns:", len(df_raw.columns))

display(df_raw.head())

Rows: 261
Columns: 11

,invoice_id,invoice_date,erp_customer_code,erp_customer_name,cluster,product_code,product_name,currency,quantity,unit_price_local,contract_id
0,INV-10146,2026-04-25,A000,HC Group A,UK,P02,Mask,GBP,34,225,CT-01
1,INV-10164,2026-03-17,A000,HC Group A,UK,P02,Mask,GBP,30,370,CT-01
2,INV-10176,2026-07-25,A000,HC Group A,UK,P02,Mask,GBP,19,370,CT-01
3,INV-10212,2026-01-27,A000,HC Group A,UK,P02,Mask,GBP,11,700,CT-01
4,INV-10236,2026-09-06,A000,HC Group A,UK,P02,Mask,GBP,27,110,CT-01

In [3]:

print("DATA QUALITY REPORT")
print("-------------------")

print("Total records:", len(df_raw))

print("Duplicate invoices:",
      df_raw.duplicated(subset=["invoice_id"]).sum())

print("\nMissing values by column:")
print(df_raw.isnull().sum())

print("\nData types:")
print(df_raw.dtypes)

print("\nSample invoice records:")
display(df_raw.head(10))

DATA QUALITY REPORT
-------------------
Total records: 261
Duplicate invoices: 1

Missing values by column:
invoice_id           0
invoice_date         0
erp_customer_code    0
erp_customer_name    1
cluster              0
product_code         0
product_name         0
currency             0
quantity             0
unit_price_local     0
contract_id          0
dtype: int64

Data types:
invoice_id           object
invoice_date         dbdate
erp_customer_code    object
erp_customer_name    object
cluster              object
product_code         object
product_name         object
currency             object
quantity              Int64
unit_price_local      Int64
contract_id          object
dtype: object

Sample invoice records:

,invoice_id,invoice_date,erp_customer_code,erp_customer_name,cluster,product_code,product_name,currency,quantity,unit_price_local,contract_id
0,INV-10146,2026-04-25,A000,HC Group A,UK,P02,Mask,GBP,34,225,CT-01
1,INV-10164,2026-03-17,A000,HC Group A,UK,P02,Mask,GBP,30,370,CT-01
2,INV-10176,2026-07-25,A000,HC Group A,UK,P02,Mask,GBP,19,370,CT-01
3,INV-10212,2026-01-27,A000,HC Group A,UK,P02,Mask,GBP,11,700,CT-01
4,INV-10236,2026-09-06,A000,HC Group A,UK,P02,Mask,GBP,27,110,CT-01
5,INV-10044,2026-02-13,A001,HC Group B,France,P02,Mask,EUR,29,700,CT-02
6,INV-10110,2026-07-10,A001,HC Group B,France,P02,Mask,EUR,3,370,CT-02
7,INV-10251,2026-03-07,A001,HC Group B,France,P02,Mask,EUR,8,225,CT-02
8,INV-10086,2026-04-28,A002,HC Group C,Germany,P02,Mask,EUR,25,700,CT-03
9,INV-10107,2026-05-18,A002,HC Group C,Germany,P02,Mask,EUR,18,370,CT-03

In [4]:

# STEP 6: Data Quality Profiling

print("=== DATA QUALITY REPORT ===")

print("\n1. Total records:", len(df_raw))

print("\n2. Duplicate invoice IDs:")
print(df_raw["invoice_id"].duplicated().sum())

print("\n3. Missing values:")
display(df_raw.isnull().sum().to_frame("missing_count"))

print("\n4. Column data types:")
display(df_raw.dtypes.to_frame("data_type"))

print("\n5. Currency values:")
if "currency" in df_raw.columns:
    display(df_raw["currency"].value_counts(dropna=False))

print("\n6. Sample records:")
display(df_raw.head(10))

=== DATA QUALITY REPORT ===

1. Total records: 261

2. Duplicate invoice IDs:
1

3. Missing values:

                   missing_count
invoice_id                     0
invoice_date                   0
erp_customer_code              0
erp_customer_name              1
cluster                        0
product_code                   0
product_name                   0
currency                       0
quantity                       0
unit_price_local               0
contract_id                    0

4. Column data types:

                  data_type
invoice_id           object
invoice_date         dbdate
erp_customer_code    object
erp_customer_name    object
cluster              object
product_code         object
product_name         object
currency             object
quantity              Int64
unit_price_local      Int64
contract_id          object

5. Currency values:

currency
EUR     201
GBP      58
EURO      2
Name: count, dtype: int64

6. Sample records:

,invoice_id,invoice_date,erp_customer_code,erp_customer_name,cluster,product_code,product_name,currency,quantity,unit_price_local,contract_id
0,INV-10146,2026-04-25,A000,HC Group A,UK,P02,Mask,GBP,34,225,CT-01
1,INV-10164,2026-03-17,A000,HC Group A,UK,P02,Mask,GBP,30,370,CT-01
2,INV-10176,2026-07-25,A000,HC Group A,UK,P02,Mask,GBP,19,370,CT-01
3,INV-10212,2026-01-27,A000,HC Group A,UK,P02,Mask,GBP,11,700,CT-01
4,INV-10236,2026-09-06,A000,HC Group A,UK,P02,Mask,GBP,27,110,CT-01
5,INV-10044,2026-02-13,A001,HC Group B,France,P02,Mask,EUR,29,700,CT-02
6,INV-10110,2026-07-10,A001,HC Group B,France,P02,Mask,EUR,3,370,CT-02
7,INV-10251,2026-03-07,A001,HC Group B,France,P02,Mask,EUR,8,225,CT-02
8,INV-10086,2026-04-28,A002,HC Group C,Germany,P02,Mask,EUR,25,700,CT-03
9,INV-10107,2026-05-18,A002,HC Group C,Germany,P02,Mask,EUR,18,370,CT-03

In [6]:

# Find rows with missing customer names
print("MISSING CUSTOMER NAMES")
display(
    df_raw[df_raw["erp_customer_name"].isna()]
)

# Find invoices that appear more than once
print("\nDUPLICATE INVOICE IDS")
display(
    df_raw[df_raw.duplicated(
        subset=["invoice_id"],
        keep=False
    )]
)

MISSING CUSTOMER NAMES

,invoice_id,invoice_date,erp_customer_code,erp_customer_name,cluster,product_code,product_name,currency,quantity,unit_price_local,contract_id
180,INV-10074,2026-07-27,A003,None,Ireland,P01,Sleep Device,EUR,11,950,CT-04

DUPLICATE INVOICE IDS

,invoice_id,invoice_date,erp_customer_code,erp_customer_name,cluster,product_code,product_name,currency,quantity,unit_price_local,contract_id
107,INV-10017,2026-06-17,A001,HC Group B,France,P03,Replacement Supplies,EUR,27,700,CT-02
112,INV-10017,2026-06-17,A001,HC Group B,France,P03,Replacement Supplies,EUR,27,700,CT-02

In [7]:

print("Currency distribution:")
display(df_raw["currency"].value_counts(dropna=False))

print("\nInvalid currency records:")
display(
    df_raw[
        ~df_raw["currency"].isin(["EUR", "GBP"])
    ]
)

Currency distribution:

currency
EUR     201
GBP      58
EURO      2
Name: count, dtype: int64

Invalid currency records:

,invoice_id,invoice_date,erp_customer_code,erp_customer_name,cluster,product_code,product_name,currency,quantity,unit_price_local,contract_id
212,INV-10130,2026-07-16,A001,Healthcare Group B,France,P01,Sleep Device,EURO,21,110,CT-02
248,INV-10036,2026-02-02,A007,Healthcare Group H Ltd,Germany,P01,Sleep Device,EURO,14,700,CT-08

cleaning

In [8]:

# Preserve original raw data
df_clean = df_raw.copy()

# 1. Remove exact duplicate rows
before = len(df_clean)
df_clean = df_clean.drop_duplicates().copy()

print("Duplicates removed:", before - len(df_clean))

# 2. Standardise currency codes
df_clean["currency"] = (
    df_clean["currency"]
    .astype("string")
    .str.strip()
    .str.upper()
    .replace({"EURO": "EUR"})
)

# 3. Check remaining currencies
print("\nCLEANED CURRENCY DISTRIBUTION")
display(df_clean["currency"].value_counts(dropna=False))

# 4. Verify invoice uniqueness
print("\nRemaining duplicate invoice IDs:",
      df_clean["invoice_id"].duplicated().sum())

# 5. Verify invalid currencies
print("Invalid currencies:",
      (~df_clean["currency"].isin(["EUR", "GBP"])).sum())

print("\nCleaned records:", len(df_clean))

Duplicates removed: 1

CLEANED CURRENCY DISTRIBUTION

currency
EUR    202
GBP     58
Name: count, dtype: Int64

Remaining duplicate invoice IDs: 0
Invalid currencies: 0

Cleaned records: 260

In [9]:

master = client.query("""
SELECT *
FROM `emea-strategic-analytics.emea_analytics.account_master`
""").to_dataframe()

print("ACCOUNT MASTER COLUMN NAMES:")
print(master.columns.tolist())

print("\nFIRST 10 MASTER RECORDS:")
display(master.head(10))

ACCOUNT MASTER COLUMN NAMES:
['account_id', 'canonical_account_name', 'parent_account_id', 'home_cluster', 'active_flag']

FIRST 10 MASTER RECORDS:

,account_id,canonical_account_name,parent_account_id,home_cluster,active_flag
0,A001,Healthcare Group B,EMEA-TOP10,France,True
1,A006,Healthcare Group G,EMEA-TOP10,France,True
2,A002,Healthcare Group C,EMEA-TOP10,Germany,True
3,A007,Healthcare Group H,EMEA-TOP10,Germany,True
4,A003,Healthcare Group D,EMEA-TOP10,Ireland,True
5,A008,Healthcare Group I,EMEA-TOP10,Ireland,True
6,A004,Healthcare Group E,EMEA-TOP10,Spain,True
7,A009,Healthcare Group J,EMEA-TOP10,Spain,True
8,A000,Healthcare Group A,EMEA-TOP10,UK,True
9,A005,Healthcare Group F,EMEA-TOP10,UK,True

In [10]:

# STEP 12: Resolve ERP customer identities
# using the governed account master

# Ensure one approved master record per account ID
assert master["account_id"].is_unique

# Bring master details into the cleaned billing dataset
df_enriched = df_clean.merge(
    master[[
        "account_id",
        "canonical_account_name",
        "parent_account_id",
        "home_cluster"
    ]],
    left_on="erp_customer_code",
    right_on="account_id",
    how="left",
    validate="many_to_one",
    indicator=True
)

# Identify records that could not be mapped
unmatched = df_enriched[
    df_enriched["_merge"] != "both"
].copy()

# Use the approved master name for matched records
df_enriched["resolved_customer_name"] = (
    df_enriched["canonical_account_name"]
)

# Flag missing or inconsistent source names
source_name = (
    df_enriched["erp_customer_name"]
    .fillna("")
    .astype(str)
    .str.strip()
    .str.casefold()
)

master_name = (
    df_enriched["canonical_account_name"]
    .fillna("")
    .astype(str)
    .str.strip()
    .str.casefold()
)

df_enriched["customer_name_mismatch"] = (
    source_name != master_name
)

print("Total invoice records:", len(df_enriched))
print("Mapped records:",
      (df_enriched["_merge"] == "both").sum())
print("Unmatched records:", len(unmatched))
print("Source name differences:",
      df_enriched["customer_name_mismatch"].sum())

display(
    df_enriched[[
        "invoice_id",
        "erp_customer_code",
        "erp_customer_name",
        "resolved_customer_name",
        "customer_name_mismatch"
    ]].head(10)
)

Total invoice records: 260
Mapped records: 259
Unmatched records: 1
Source name differences: 173

,invoice_id,erp_customer_code,erp_customer_name,resolved_customer_name,customer_name_mismatch
0,INV-10146,A000,HC Group A,Healthcare Group A,True
1,INV-10164,A000,HC Group A,Healthcare Group A,True
2,INV-10176,A000,HC Group A,Healthcare Group A,True
3,INV-10212,A000,HC Group A,Healthcare Group A,True
4,INV-10236,A000,HC Group A,Healthcare Group A,True
5,INV-10044,A001,HC Group B,Healthcare Group B,True
6,INV-10110,A001,HC Group B,Healthcare Group B,True
7,INV-10251,A001,HC Group B,Healthcare Group B,True
8,INV-10086,A002,HC Group C,Healthcare Group C,True
9,INV-10107,A002,HC Group C,Healthcare Group C,True

In [11]:

display(
    df_enriched.loc[
        df_enriched["invoice_id"] == "INV-10074",
        [
            "invoice_id",
            "erp_customer_code",
            "erp_customer_name",
            "resolved_customer_name",
            "home_cluster"
        ]
    ]
)

,invoice_id,erp_customer_code,erp_customer_name,resolved_customer_name,home_cluster
179,INV-10074,A003,None,Healthcare Group D,Ireland

In [12]:

print("UNMATCHED CUSTOMER RECORD")

display(
    df_enriched.loc[
        df_enriched["_merge"] == "left_only",
        [
            "invoice_id",
            "erp_customer_code",
            "erp_customer_name",
            "cluster",
            "currency",
            "quantity",
            "unit_price_local"
        ]
    ]
)

UNMATCHED CUSTOMER RECORD

,invoice_id,erp_customer_code,erp_customer_name,cluster,currency,quantity,unit_price_local
115,INV-10062,UNKNOWN,HC Group D,Ireland,EUR,21,950

In [13]:

# Load exchange rates from BigQuery
fx_data = client.query("""
SELECT *
FROM `emea-strategic-analytics.emea_analytics.fx_rates`
""").to_dataframe()

print("FX TABLE COLUMNS")
print(fx_data.columns.tolist())

print("\nFX SAMPLE")
display(fx_data.head(10))

FX TABLE COLUMNS
['fx_month', 'from_currency', 'to_currency', 'eur_per_unit']

FX SAMPLE

  fx_month from_currency to_currency  eur_per_unit
0  2026-01           EUR         EUR         1.000
1  2026-02           EUR         EUR         1.000
2  2026-03           EUR         EUR         1.000
3  2026-04           EUR         EUR         1.000
4  2026-05           EUR         EUR         1.000
5  2026-06           EUR         EUR         1.000
6  2026-07           EUR         EUR         1.000
7  2026-08           EUR         EUR         1.000
8  2026-09           EUR         EUR         1.000
9  2026-01           GBP         EUR         1.155

In [14]:

# STEP 16: Monthly currency conversion

import pandas as pd
import numpy as np

# Create a working copy
df_fx = df_enriched.copy()

# Convert invoice dates into monthly keys
df_fx["invoice_date"] = pd.to_datetime(
    df_fx["invoice_date"]
)

df_fx["fx_month"] = (
    df_fx["invoice_date"]
    .dt.strftime("%Y-%m")
)

# Prepare monthly FX rates
rates = fx_data.copy()

rates["fx_month"] = (
    rates["fx_month"]
    .astype(str)
    .str[:7]
)

rates["from_currency"] = (
    rates["from_currency"]
    .astype(str)
    .str.strip()
    .str.upper()
)

rates = rates[
    rates["to_currency"] == "EUR"
].copy()

# Prevent duplicated FX matches
assert not rates.duplicated(
    ["fx_month", "from_currency"]
).any(), "Duplicate monthly FX rates detected"

# Join invoices to monthly exchange rates
df_fx = df_fx.merge(
    rates[[
        "fx_month",
        "from_currency",
        "eur_per_unit"
    ]],
    left_on=["fx_month", "currency"],
    right_on=["fx_month", "from_currency"],
    how="left",
    validate="many_to_one"
)

# Calculate local and EUR revenue
df_fx["revenue_local"] = (
    pd.to_numeric(df_fx["quantity"]) *
    pd.to_numeric(df_fx["unit_price_local"])
)

df_fx["revenue_eur"] = (
    df_fx["revenue_local"] *
    pd.to_numeric(df_fx["eur_per_unit"])
).round(2)

# Flag records that cannot be reliably reported
df_fx["rejection_reason"] = ""

df_fx.loc[
    df_fx["account_id"].isna(),
    "rejection_reason"
] += "Unmatched account; "

df_fx.loc[
    df_fx["eur_per_unit"].isna(),
    "rejection_reason"
] += "Missing FX rate; "

df_fx.loc[
    df_fx["revenue_local"].isna() |
    (df_fx["revenue_local"] <= 0),
    "rejection_reason"
] += "Invalid revenue; "

# Split accepted and rejected records
fact_revenue = df_fx[
    df_fx["rejection_reason"] == ""
].copy()

rejected_records = df_fx[
    df_fx["rejection_reason"] != ""
].copy()

print("Original raw records:", len(df_raw))
print("After deduplication:", len(df_clean))
print("Accepted invoices:", len(fact_revenue))
print("Quarantined invoices:", len(rejected_records))

print("\nTotal accepted revenue EUR:",
      round(fact_revenue["revenue_eur"].sum(), 2))

print("\nQuarantined records:")
display(rejected_records[[
    "invoice_id",
    "erp_customer_code",
    "currency",
    "rejection_reason"
]])

print("\nSample validated revenue:")
display(fact_revenue[[
    "invoice_id",
    "resolved_customer_name",
    "currency",
    "revenue_local",
    "eur_per_unit",
    "revenue_eur"
]].head())

Original raw records: 261
After deduplication: 260
Accepted invoices: 257
Quarantined invoices: 3

Total accepted revenue EUR: 2399181.24

Quarantined records:

    invoice_id erp_customer_code currency     rejection_reason
86   INV-10022              A006      EUR    Invalid revenue;
115  INV-10062           UNKNOWN      EUR  Unmatched account;
183  INV-10089              A001      EUR    Invalid revenue;

Sample validated revenue:

,invoice_id,resolved_customer_name,currency,revenue_local,eur_per_unit,revenue_eur
0,INV-10146,Healthcare Group A,GBP,7650,1.170,8950.5
1,INV-10164,Healthcare Group A,GBP,11100,1.165,12931.5
2,INV-10176,Healthcare Group A,GBP,7030,1.185,8330.55
3,INV-10212,Healthcare Group A,GBP,7700,1.155,8893.5
4,INV-10236,Healthcare Group A,GBP,2970,1.195,3549.15

In [15]:

# Reconciliation checks

assert (
    len(fact_revenue) + len(rejected_records)
    == len(df_clean)
), "Record reconciliation failed!"

assert fact_revenue["invoice_id"].is_unique, (
    "Duplicate invoice IDs in fact table!"
)

assert fact_revenue["revenue_eur"].notna().all(), (
    "Missing converted revenue!"
)

print("RECONCILIATION PASSED")
print("Accepted:", len(fact_revenue))
print("Rejected:", len(rejected_records))
print("Total:", len(df_clean))

RECONCILIATION PASSED
Accepted: 257
Rejected: 3
Total: 260

In [16]:

# STEP 18: Load transformed data into BigQuery

from google.cloud import bigquery

project_id = "emea-strategic-analytics"
dataset_id = "emea_analytics"

# Select clean reporting columns
revenue_to_upload = fact_revenue[[
    "invoice_id",
    "invoice_date",
    "account_id",
    "resolved_customer_name",
    "parent_account_id",
    "home_cluster",
    "product_code",
    "product_name",
    "contract_id",
    "currency",
    "quantity",
    "unit_price_local",
    "fx_month",
    "eur_per_unit",
    "revenue_local",
    "revenue_eur"
]].copy()

# Standardise dates and numeric types
revenue_to_upload["invoice_date"] = pd.to_datetime(
    revenue_to_upload["invoice_date"]
).dt.date

for col in [
    "quantity", "unit_price_local",
    "eur_per_unit", "revenue_local", "revenue_eur"
]:
    revenue_to_upload[col] = pd.to_numeric(
        revenue_to_upload[col]
    ).astype("float64")

# Keep a focused rejected-record audit table
rejected_to_upload = rejected_records[[
    "invoice_id",
    "erp_customer_code",
    "erp_customer_name",
    "currency",
    "rejection_reason"
]].copy()

# BigQuery upload configuration
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE"
)

# Upload accepted invoices
revenue_table = (
    f"{project_id}.{dataset_id}.fact_revenue"
)

job = client.load_table_from_dataframe(
    revenue_to_upload,
    revenue_table,
    job_config=job_config
)
job.result()

print("Uploaded:", revenue_table)
print("Rows:", len(revenue_to_upload))

# Upload rejected invoices
rejected_table = (
    f"{project_id}.{dataset_id}.rejected_records"
)

job = client.load_table_from_dataframe(
    rejected_to_upload,
    rejected_table,
    job_config=job_config
)
job.result()

print("Uploaded:", rejected_table)
print("Rows:", len(rejected_to_upload))

Uploaded: emea-strategic-analytics.emea_analytics.fact_revenue
Rows: 257
Uploaded: emea-strategic-analytics.emea_analytics.rejected_records
Rows: 3